// Code generated by Slice Machine. DO NOT EDIT.

import HeroSlice from './HeroSlice';
import ImageGrid from './ImageGrid';
import ImageGrid2 from './ImageGrid2';

export {
	HeroSlice,
	ImageGrid,
	ImageGrid2,
};

export const components = {
	hero_slice: HeroSlice,
	image_grid: ImageGrid,
	image_grid2: ImageGrid2,
};
